import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/navbar";
import "./globals.css";
import SEO from "@/components/head";
import { motion, AnimatePresence } from "framer-motion";
import { usePathname } from "next/navigation";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    const pathname = usePathname(); 

    return (
        <html lang="en">
            <SEO />
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-gray-900 to-black text-white min-h-screen`}>
                <Navbar />
                <AnimatePresence mode="wait">
                    <motion.main
                        key={pathname} // Beri key agar effect bekerja di setiap perubahan halaman
                        className="container mx-auto px-4"
                        initial={{ opacity: 0, x: pathname === "/" ? 100 : -100 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, x: pathname === "/" ? -100 : 100 }}
                        transition={{ duration: 0.4, ease: "easeInOut" }}
                    >
                        {children}
                    </motion.main>
                </AnimatePresence>
            </body>
        </html>
    );
}
